### ISSUE TITLE
Warning: call_user_func_array()

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/simple-author-box#1]
I am not sure when this error popped up, may have been after the latest auto update from WordPress. I am seeing this in below Simple Author Box.

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function ‘wps_theme_author_box’ not found or invalid function name in /home/account/public_html/wp-includes/class-wp-hook.php on line 298

I see this when debug = true.

Is there a fix for this?

**Comment by giucu91** [comment]
@cristianraiber I didn't find the "wps_theme_author_box" string in our plugin. Maybe this has been fixed in a previous version.

**Comment by cristianraiber** [comment]
Marking as closed.
