### ISSUE TITLE
incompatibility with Content Blocks (Custom Post Widget)

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/simple-author-box#100]
https://wordpress.org/plugins/custom-post-widget/

There is a repeated Author Box everywhere there is a Content Block shortcode.

**Comment by giucu91** [comment]
@razvanaldea89 please give us some examples on how to use this in order to add it to the FAQ on wp.org ?

**Comment by razvanaldea89** [comment]
In the case of a widget, when inserting the widget in the widget area and selecting the content block to display there is a checkbox titled "Do not apply content filters". Checking this will not dispaly the author box. 
In the case of using a shortcode, example [content_block id=41],  the shortcode to use for not displaying the author is  [content_block id=41  suppress_content_filters=true] or [content_block id=41  suppress_filters=true], both work depending on scenarios.

**Comment by giucu91** [comment]
Added in readme.txt
