### ISSUE TITLE
Author name and description showing in Post Excerpt in Category

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/simple-author-box#101]
feedback: When i select a Category that views all entries in it i see that the Author name and his description are taken into the entry excerpt – if the excerpt is shorter that the limit it will be filled with Author Name and Description. It happens only in Categories, on the Homepage it works fine. If i turn off Simple Author Box or if i use other Author plugin the Categories looks fine too.

**Comment by razvanaldea89** [comment]
Experienced this with "Divi" theme and probably other themes, twenty seventeen looks fine. Think we should add a new option to disable author box on categories. Think this is a issue with strip tags.

**Comment by cristianraiber** [comment]
This now works as it should :) GJ @razvanaldea89
