### ISSUE TITLE
Add telegram  link

### ISSUE THREAD

**Issue by lmillucci** [MachoThemes/simple-author-box#109]

**Comment by giucu91** [comment]
Hello @lmillucci can you please create a pull request for this issue ?

**Comment by lmillucci** [comment]
@giucu91 yes, I've already created it. https://github.com/MachoThemes/simple-author-box/pull/110

**Comment by giucu91** [comment]
@lmillucci thank you, we will make an update regarding this in roughly 2 weeks because we need to create the icon with a flat shadow.

**Comment by cristianraiber** [comment]
@razvanaldea89 - please check @lmillucci pull request and merge if it's OK.

**Comment by giucu91** [comment]
@razvanaldea89 I have merged it in your branch. please add the icons for flat shadows.
