### ISSUE TITLE
telegram icon does not change color

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/simple-author-box#116]

**Comment by razvanaldea89** [comment]
Just tested but the telegram icon changes color when set on colored.

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/53957316-b4b61b80-40e6-11e9-9ddf-898a96cec73c.png)

This happens in the backend. Also you can order all social icons alphabetically. @razvanaldea89

**Comment by razvanaldea89** [comment]
Tested and color is changing.
