### ISSUE TITLE
Add breaks to the author box text field

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/simple-author-box#23]
Hi there,

great plugin but I have a little problem now:
How can I add breaks (like ‘<br />’) to the author box text field? Or could there be a setting to get this breaks automatically if you have a line break in the bio text box?

Thanks
Uwe

---

More details here: https://wordpress.org/support/topic/how-to-add-breaks-to-the-author-box-text-field/

**Comment by uhi** [comment]
thanks for adding that to the next version.
