### ISSUE TITLE
Google Fonts always embedded

### ISSUE THREAD

**Issue by akerd** [MachoThemes/simple-author-box#27]
Hello, thank you for the plugin first, it is really helpful.

I noticed that Google Fonts is always embedded even if there is not Family set.

Example: 

`<link rel='stylesheet' id='sab-author-name-font-css'  href='http://fonts.googleapis.com/css?family=none:400,700,400italic,700italicsubset=None' type='text/css' media='all' />`

I modified the code in function saboxplugin_author_box_font() to fix it and enque the style only if requested.

```
if ( get_option( 'sab_box_name_font' ) <> 'none'  ) {
	wp_enqueue_style( 'sab-author-name-font', $sab_protocol . '://fonts.googleapis.com/css?family=' . str_replace( ' ', '+', $sab_author_font ) . ':400,700,400italic,700italic' . $sab_subset, array(), null );
}

if ( get_option( 'sab_box_desc_font' ) <> 'none'  ) {
	wp_enqueue_style( 'sab-author-desc-font', $sab_protocol . '://fonts.googleapis.com/css?family=' . str_replace( ' ', '+', $sab_desc_font ) . ':400,700,400italic,700italic' . $sab_subset, array(), null );
}

if ( isset( $options['sab_web'] ) and (get_option( 'sab_box_web_font' ) <> 'none')  ) {
	wp_enqueue_style( 'sab-author-web-font', $sab_protocol . '://fonts.googleapis.com/css?family=' . str_replace( ' ', '+', $sab_web_font ) . ':400,700,400italic,700italic' . $sab_subset, array(), null );
}

```

I see that you are rewriting some code so I am not sure I can easily contribute to this Git.

Please, check the suggestion and if possible add a fix when you have time.

**Comment by cristianraiber** [comment]
@akerd - this is already fixed in the latest version of the plugin :) It's just not released, though, it's committed to the master branch of this repo.
