### ISSUE TITLE
custom icons

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/simple-author-box#37]
REQUEST: Add custom icon by inserting name of fontawesome icon. This should not be too hard to implement — add an item to the dropdown for “custom” which displays a text input for the fontawesome icon name. Then we could add links to just about anything, instead of the limited list which this plugin offers.

See ticket here: https://wordpress.org/support/topic/website-icon-or-custom-icon/

**Comment by cristianraiber** [comment]
This should be a PRO feature.
