### ISSUE TITLE
Exclude pages 

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/simple-author-box#5]
Curious if this is going to be updated.

The author plugin is showing up on every page I make and I don’t want it to show up on Pages. It would be nice to have a setting button to exclude Pages.

This is also affecting the Woocommerce Product pages.

Update: I was able to assign a blank user to Pages to hide the author box. This go-around does not work for the Woocommerce Product pages. There is no option to reassign the author.

---

https://wordpress.org/support/topic/exclude-pages-setting-button-needed/

**Comment by cristianraiber** [comment]
Iterate over CPTs and allow the user to disable per CPT.

**Comment by cristianraiber** [comment]
@giucu91 - let's move this to the PRO version.

**Comment by giucu91** [comment]
@cristianraiber this is actually in the PRO version.

**Comment by cristianraiber** [comment]
@giucu91 - marking as closed.
