### ISSUE TITLE
Other features

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/simple-author-box#7]
- possibilty of put in bold the name of author
– possibilty of modify border-top color of social bar
– possibilty of modify margins (top and bottom) of the all box
– add a email of author (as social icon or below the web with the same style)

And posibilty to see the last ‘x’ posts of author

**Comment by giucu91** [comment]
@cristianraiber the possibility to change the margin was there, but was hidden if you don't select to insert manually the box. Now it's visible.
I have added the possibility to add the author's email.

About the border's top color, should we add an option for all the borders or just for the social top border ?

**Comment by cristianraiber** [comment]
@giucu91 - for all the borders. one color picker for all
