### ISSUE TITLE
update FontAwesome to 5.0

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/simple-author-box#70]
The Goodreads icon was added in 5.0 and because at the moment we have 4.7 it leaves it empty:
https://gyazo.com/c6fa8c6f097b45c341963780ecd71c2f

**Comment by cristianraiber** [comment]
SAB won't get FA 5.0 anytime soon. FA5.0 is a horror story.

**Comment by giucu91** [comment]
@cristianraiber maybe we can download FA5 icons' svg and make our own font in order to avoid the compatibility issue.
