### ISSUE TITLE
Missing argument 6 for Simple_Author_Box

### ISSUE THREAD

**Issue by roman5527** [MachoThemes/simple-author-box#71]
Hi, i see error: 
`Warning: Missing argument 6 for Simple_Author_Box::replace_gravatar_image() in /nfsmnt/hosting1_1/3/8/38f572f3-3b1d-49db-a132-0516739706aa/ekonoom.sk/web/wp-content/plugins/simple-author-box/inc/class-simple-author-box.php on line 86`

i have wordpress 4.9.6 

tahnks

**Comment by cristianraiber** [comment]
@roman5527 - which version of SAB do you use?

**Comment by roman5527** [comment]
hi, 2.0.9

**Comment by cristianraiber** [comment]
@roman5527 - could you please let me know if you have `WP_DEBUG` set to `true` in your wp-config.php file?

**Comment by roman5527** [comment]
Hi, i set `WP_DEBUG` to `ture`

**Comment by roman5527** [comment]
hi, can you help me fix it ?

**Comment by cristianraiber** [comment]
Please see this: https://wordpress.org/support/topic/replace_gravatar_image-missing-argument-6/
