### ISSUE TITLE
Error class-simple-author-box.php

### ISSUE THREAD

**Issue by roman5527** [MachoThemes/simple-author-box#74]
Hi, i have some errors in my blog . You can see : [http://www.ekonoom.sk/dan-z-prijmov/neviete-ako-na-rocne-zuctovanie-v-roku-2018-objavte-svoje-povinnosti/](url)

Errors:  
`Notice: Undefined index: size in /nfsmnt/hosting1_1/3/8/38f572f3-3b1d-49db-a132-0516739706aa/ekonoom.sk/web/wp-content/plugins/simple-author-box/inc/class-simple-author-box.php on line 116

Notice: Undefined index: found_avatar in /nfsmnt/hosting1_1/3/8/38f572f3-3b1d-49db-a132-0516739706aa/ekonoom.sk/web/wp-content/plugins/simple-author-box/inc/class-simple-author-box.php on line 118

Notice: Undefined index: class in /nfsmnt/hosting1_1/3/8/38f572f3-3b1d-49db-a132-0516739706aa/ekonoom.sk/web/wp-content/plugins/simple-author-box/inc/class-simple-author-box.php on line 122`

Can you help me please fix it ? 

thanks

**Comment by roman5527** [comment]
Hi, any new idea ? thanks

**Comment by cristianraiber** [comment]
@roman5527 - I will release an update to address this very soon.

**Comment by roman5527** [comment]
Hi, is somthings new ? new version ? fix it ? thanks

**Comment by cristianraiber** [comment]
@roman5527 - new version hasn't been uploaded yet. Will update soon, stay tuned!

**Comment by bsrafael** [comment]
Hello!
Any updates on this?
