### ISSUE TITLE
Social Icons Broken

### ISSUE THREAD

**Issue by tilmanbremer** [MachoThemes/simple-author-box#81]
SAB: 2.0.9
WP: 4.9.8

The social links are broken and errors are displayed instead, see screenshot. Is it possible that is has something to do with FA 5? With Firefox Inspector, I could see that FA is actually loaded twice, once from my server:
/wp-content/themes/customizr/assets/shared/fonts/fa/css/fontawesome-all.min.css?ver=4.1.12
and once from google like that:
https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css?ver=4.9.8
![sab](https://user-images.githubusercontent.com/20415107/44388987-eb9d5900-a529-11e8-9501-36a96acc687a.PNG)

**Comment by cristianraiber** [comment]
@tilmanbremer - this is happening when running the "Customizr" theme (https://wordpress.org/themes/customizr/) , right? Need to make sure before I test it out.

**Comment by tilmanbremer** [comment]
Sorry, yes, the theme I am using is Customizr 4.1.12. Forgot to mention that.
