### ISSUE TITLE
profile image in the comments section

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/simple-author-box#96]
custom profile image is much larger than it should be in the comments section
![ola2](https://user-images.githubusercontent.com/26008574/47641453-c99a0580-db6e-11e8-9f16-1523d198f0d0.png)
![Uploading ola1.png…]()

**Comment by giucu91** [comment]
Aceeasi ca aici : https://github.com/MachoThemes/simple-author-box/issues/97
