### ISSUE TITLE
profile image in dashboard

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/simple-author-box#97]
![screnshot1](https://user-images.githubusercontent.com/26008574/47773189-ead72f00-dcf1-11e8-954c-a6738d81556d.png)

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/48955534-13e88980-ef57-11e8-8e5d-af79cf88427b.png)

Nu mai apare deloc acum.

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/49512860-e0332b00-f897-11e8-8552-f45cc526efd5.png)

**Comment by cristianraiber** [comment]
This seems to be working fine now.
