### ISSUE TITLE
add Whatsapp

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/simple-author-box#99]

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/48955435-93c22400-ef56-11e8-970e-3d4291c046e1.png)

Culoarea de fundal ar trebui sa fie verde, culoarea bramdului. Pentru a lua culoarea intra aici : https://brandcolors.net/b/whatsapp

De asemenea nu se vede shadowul.

**Comment by giucu91** [comment]
**Show a thin border on colored social icons** is not working with the whatsapp icon.
![image](https://user-images.githubusercontent.com/7580330/49397685-f7153880-f744-11e8-85c6-0ce6fd2e72cd.png)
![image](https://user-images.githubusercontent.com/7580330/49397714-0c8a6280-f745-11e8-8527-9dce29b687e5.png)

**Comment by giucu91** [comment]
Added in 2.1.4
